### ISSUE TITLE
Some bugs and Ideas.

### ISSUE THREAD

**Issue by Kikasuru** [Yackerw/NetXEngine#11]
Hey, I really love your work with this project! Me and my friend were playing it last night and we noticed some really annoying bugs while playing, so I listed all of the ones I noticed while playing, and ideas on how to fix them. I also added some other cool ideas to think about as well!

Anyways, here's that list.
https://docs.google.com/document/d/13eJEo5rGsf_SoopOvkVdFOrUD-6mno5JBTMrnztiqMM/edit?usp=sharing

I hope you consider some of my ideas!

**Comment by Yackerw** [comment]
-I don't know what version you may be playing where this doesn't happen (or what otherwise could've caused it) but I just tested on the latest version and item/health syncing on join should be working. If it's not, then that's definitely a problem
-Death problems are known, though deemed "low priority"
-Host being the only one able to interact with things is a very intentional design choice, to prevent random players from trolling with repeated event execution.
-Any TSC event will resurrect players, which means health regenerators already do!
-Custom skins are planned
-Other gamemodes is something that's been brought up before, but for right now the only plans are co-operative play.
-A custom map/script downloader would be added if the native mod support ever got any better, which is itself a beast to tackle.
-Space between name - the <> around the name was already kinda supposed to act like that, but I'll consider this one.
-HUD for other players health: there may be something for that soon
-Singleplayer skins: I've basically left the single player game identical to what it was in Evo, but I'll consider this one as well.
-Port settings I may eventually add, but is currently low priority.

Thank you for the feedback.

**Comment by Kikasuru** [comment]
Thank you for reading my ideas, and good luck to you on this project!

**Comment by Kikasuru** [comment]
Just went into a localhost game, and it does transfer items, I just had to select them via the inventory, sorry about the trouble!
